### ISSUE TITLE
Concider ember-ajax

### ISSUE THREAD

**Issue by sukima** [rtablada/ember-rolodex#1]
All Ember 2.13 apps by default have the [`ember-ajax`](https://github.com/ember-cli/ember-ajax) while the `fetch` API is not universally supported. Perhaps we should start AJAX fetch with ember-ajax instead of fetch before introducing ember-data.

**Comment by rtablada** [comment]
The reason I choose to use `fetch` is that it is supported across most browsers. I have to 🤔  about IE11 support I'm guessing maybe importing `fetch` and installing `ember-fetch` instead.

The reason I choose not to use `ember-ajax` is that it is another new concept for new devs compared to something that is baked into the standard ES6+.

**Comment by sukima** [comment]
Fair enough.
